# Generated by Django 2.2.6 on 2019-10-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191011_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='conversion_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gold_member',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Artist', 'Artist'), ('Gamer', 'Gamer'), ('Movie Buff', 'Movie Buff'), ('Student', 'Student'), ('Normal User', 'Normal User')], default='Normal User', max_length=20),
        ),
    ]
