# Generated by Django 2.2.6 on 2019-10-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191013_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chosen_product',
            field=models.CharField(blank=True, default='none', max_length=10),
        ),
    ]
