# Generated by Django 2.2.6 on 2019-10-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'category', 'price')},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Enter category name of product', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='conversion_rate',
            field=models.IntegerField(default=0),
        ),
    ]
