# Generated by Django 2.2.6 on 2019-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191012_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='products/large/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='products/small/%Y/%m/%d'),
        ),
    ]
