# Generated by Django 2.2.4 on 2019-10-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191013_2029'),
        ('shop', '0007_auto_20191013_2306'),
    ]

    operations = [
    ]
